---
title: "Tidy Tuesday Week 42 - Stranger Things Dialogue"
author: "Dominik Ziaja"
date: "2022-10-18"
output:
  html_document:
    toc: true
    number_section: true
    toc_float: true
    code_folding: hide
    theme: cerulean
---

# Load in necessary stuff
```{r}
# Load in the tidyverse
library(ggplot2)
library(dplyr)
library(tidyr)
library(readr)
library(purrr)
library(tibble)
library(stringr)
library(forcats)
library(tidytext)
library(grid)
library(ggfx)
library(ggtext)
library(showtext)
```
# Setting up Fonts to use
```{r}
font_add("benguiat", "BenguiatFont/BenguiatStd-Book.otf")
font_text <- "benguiat"
# get the path of font awesome
fa_brands_path <- systemfonts::font_info(family = "Font Awesome 6 Brands")[["path"]]
# add the font under the name of "fa-brands"
font_add(family = "fa-brands", fa_brands_path)

showtext_auto()
```

# Define colors used
```{r}
geom.colors <- "#872222"
geom.positive.glow.colors <- "#e6dcdc"
geom.negative.glow.colors <- "#FF0000"
title.color <- "#CC0000"
plot.text.color <- "#7f0000"
```

# Write title and subtitle
```{r}
plot.title <- "Stranger Things"
plot.subtitle <- "Total negative and positive sentiment score\n of all lyrics sung during the four seasons.\n"
```

# Load data
```{r}
strangerthings_episodes <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-10-18/episodes.csv")
strangerthings_dialogues <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-10-18/stranger_things_all_dialogue.csv")
```

# Tidy dataframe
```{r}
strangerthings_songs <- strangerthings_dialogues %>%
  filter(grepl("♪", dialogue)) %>%
  distinct(raw_text, .keep_all = TRUE) %>%
  unnest_tokens(word, dialogue) %>%
  mutate(word = tolower(word)) %>%
  anti_join(get_stopwords()) %>%
  inner_join(get_sentiments("bing")) %>%
  group_by(season) %>%
  count(sentiment)
```
# Plot
```{r}
ggplot() +
  # Draw lollipops facing up with positive sentiment
  with_outer_glow(
    geom_segment(data = filter(strangerthings_songs, sentiment == "positive"),
               aes(x = season - 0.1, xend = season - 0.1, y = 0, yend = n),
               size = .7, color = geom.colors),
  colour = geom.positive.glow.colors, sigma = 10)  +
  with_outer_glow(
    geom_point(data =  filter(strangerthings_songs, sentiment == "positive"),
               aes(x = season - 0.1, y = n),
               size = 4, color = geom.colors),
  colour = geom.positive.glow.colors, sigma = 10)  +
  # Draw lollipops facing down with negative sentiment
  with_outer_glow(
    geom_segment(data = filter(strangerthings_songs, sentiment == "negative"),
               aes(x = season + 0.1, xend = season + 0.1, y = 0, yend = -n),
               size = .7, color = geom.colors),
   colour = geom.negative.glow.colors, sigma = 5) +
  with_outer_glow(
    geom_point(data =  filter(strangerthings_songs, sentiment == "negative"),
             aes(x = season + 0.1, y = -n),
             size = 4, color = geom.colors),
    colour = geom.negative.glow.colors, sigma = 5) +
  annotate("text", 
           x = c(1,2,3,4),
           y = max(strangerthings_songs$n)+16, 
           label = paste("Season",c("1", "2", "3", "4"), sep = " "),
           family = font_text,
           colour = plot.text.color) +
  geom_rect() +
  theme_void() +
  labs(title = plot.title, 
       subtitle = plot.subtitle) +
  ylab("Sentiment value") +
  scale_y_continuous(limits = c(-45, 60),
                     breaks = seq(-40,40, by = 20),
                     labels = c("-40", "-20", "0", "20", "40"),
                     ) +
  # Setting the theme of the plot
  coord_cartesian(clip = "off") +
  theme(panel.grid.major.y = element_line(colour = "#2b0707",
                                          linetype = "longdash",
                                          size = .5),
        plot.background = element_rect(fill = "#0E0D0D"),
        plot.title = element_text(size = 30,
                                  color = title.color,
                                  hjust = 0.5,
                                  family = font_text),
        plot.subtitle = element_text(size = 14,
                                     color = plot.text.color,
                                     hjust = 0.5,
                                     vjust = -0.2,
                                     family = font_text),
        axis.text.y = element_text(color = plot.text.color,
                                   margin = margin(r = 30),
                                   family = font_text),
        axis.title.y = element_text(color = plot.text.color,
                                    size = 14,
                                    margin = margin(r = 10),
                                    angle = 90,
                                    family = font_text))
```

