---
title: "TidyTuesday Week 39"
author: "Dominik Ziaja"
date: "2022-10-01"
output:
  html_document:
    toc: true
    number_section: true
    toc_float: true
    code_folding: hide
    theme: cerulean
---
# Loading necessities
```{r}
library(tidyverse)
library(showtext)
library(fontawesome)
library(stringr)
library(geojsonio)
library(rgeos)
library(broom)
library(ggtext)
```


# Setting up fonts that are used
```{r}
font_add_google("Pacifico", "paci")
font_headlines <- "paci"
font_add_google("Cormorant Garamond", "cormogar")
font_text <- "cormogar"
# get the path of font awesome
fa_brands_path <- systemfonts::font_info(family = "Font Awesome 6 Brands")[["path"]]
# add the font under the name of "fa-brands"
font_add(family = "fa-brands", fa_brands_path)

showtext_auto()
```

# Define used colors
```{r}
colorblind.scale <- c("#BBCC33",
                       "#AAAA00",
                       "#77AADD",
                       "#EE8866",
                       "#EEDD88",
                       "#FFAABB",
                       "#99DDFF",
                       "#44BB99",
                       "#DDDDDD")

background.color <- "grey80"

```

# Load data
```{r}
data.artists <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-09-27/artists.csv')
US.hexbin <- geojson_read("us_states_hexgrid.geojson", what = "sp")
```

# Data wrangling
```{r}
# First some first formatting and replacement of values
data.artists.tidied <- data.artists %>%
  mutate(artists_share = case_when(artists_n == 0 ~ 0,
                                   TRUE ~ artists_share),
         type = tolower(type)) %>%
  mutate(type_summarised = case_when(
            grepl("music", type, fixed=T) ~ "music",
            grepl("architects", type, fixed=T) ~ "architecture",
            type == "entertainers" | type == "announcers" ~ "public",
            type == "producers and directors" | 
              type == "actors" |
              type == "Dancers and Choreographers" ~ "cinema/shows",
            type == "Writers and Authros" | type == "Photographers" ~ "media",
            TRUE ~ type)) %>%
  filter(!is.na(artists_share))

#corr.m$miRNA <- factor(corr.m$miRNA, levels = corr.m$miRNA[order(corr.m$value, decreasing = FALSE)]
# Reformat hexbin map to allow merging
US.hexbin@data <- US.hexbin@data %>%
  mutate(google_name = gsub(" \\(United States\\)", "", google_name))

# make hexbin ggplotable
US.hexbin.fortified <- tidy(US.hexbin, region = "google_name")

# calculate centers of each polygon
centers <- cbind.data.frame(data.frame(gCentroid(US.hexbin, byid=T), id=US.hexbin@data$iso3166_2))

# Data for the US hexagon bin plot
data.hexa <- data.artists.tidied %>%
  filter(state != "Puerto Rico") %>%
  group_by(state, race, type_summarised) %>%
  summarise(artists_share_summed = sum(artists_share)) %>%
  group_by(state, race) %>%
  # keeps the group combination with the maximum value
  top_n(1, artists_share_summed) %>%
  group_by(state) %>%
  distinct(race, .keep_all=T) %>%
  mutate(
    type_summarised = case_when(
      artists_share_summed == 0 ~ "No artist shares",
                           TRUE ~ type_summarised),
    type_summarised = factor(type_summarised,
                                  levels = c("architecture",
                                             "cinema/shows",
                                             "dancers and choreographers",
                                             "designers",
                                             "fine artists, art directors, and animators",
                                             "music",
                                             "photographers",
                                             "public",
                                             "writers and authors",
                                             "No artist shares")),
    race = factor(race, levels = c("Asian",
                                   "African-American",
                                   "Hispanic",
                                   "White",
                                   "Other"))) %>%
  left_join(US.hexbin.fortified, by = c("state" = "id"))
```
# Set up Plot title, subtitle and caption
```{r}
title.string <- "Most dominant artist groups in the US workforce by race"

subtitle.string <- "Overall, artists across all races and the US prefer working in design. However, compared to hispanic and white artists, most African-american artists in the middle states of the US prefer to engage in music. \nAsians and other races only show in some states, scattered across the whole US, the highest number in employed artists in various disciplines."

caption.string <- "Source: Macedo et al 2022 <span style='font-family:\"fa-brands\"'>&#xf09b;</span> DoZi93/TidyTuesday #TidyTuesday #rstats"
```


# Plot the hexagon data
```{r fig.width = 20 fig.height=10}
plot.hexa.artistsshare <- ggplot(data = data.hexa) +
  geom_polygon(aes(x = long, y = lat, group = group, fill = type_summarised),
               color = "white") +
  facet_wrap(~race, scale = "free") +
  geom_text(data = centers, aes(x = x, y = y, label = id),
            size = 5) +
  scale_fill_manual("Most artists in the state's \nworkforce engage in the field of",
                    values = colorblind.scale,
                    labels = c("Architecture",
                               "Cinema and shows",
                               "Dancing",
                               "Design",
                               "Fine art and Art direction",
                               "Music",
                               "Photography",
                               "Writing",
                               "No artists in workforce")) +
  labs(title = title.string,
       subtitle = subtitle.string,
       caption = caption.string) +
  theme_classic(base_size = 24) +
  theme(
    text = element_text(family = font_text),
    panel.grid = element_blank(),
    axis.line = element_blank(),
    axis.text = element_blank(),
    axis.title = element_blank(),
    strip.background = element_blank(),
    strip.text = element_text(color = "black", size = 28),
    panel.border = element_blank(),
    plot.title = element_text(size = 38,
                              family = font_headlines,),
    plot.subtitle = element_text(family = font_text,
                                 lineheight = 0.5,
                                 size = 20),
    plot.caption = element_markdown(size = 14),
    axis.ticks = element_blank(),
    legend.title = element_text(lineheight = 0.5),
    legend.position = "top",
    legend.key.size = unit(0.15, "in")) +
  coord_cartesian(clip = "off") +
  guides(fill = guide_legend(ncol = 5))

plot(plot.hexa.artistsshare)

ggsave("hexamap.png", width = 8, height = 5.70)
```