---
title: "R Notebook"
output: html_notebook
---

# Load necessities
```{r}
library(tidyverse)
library(showtext)
library(ggtext)
library(stringr)
library(fontawesome)
```

# Load data
```{r}
WWTP.data <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-09-20/HydroWASTE_v10.csv")
```
# Load a list of continents and countries
```{r}
Continents.countries.list <- read_csv("https://raw.githubusercontent.com/dbouquin/IS_608/master/NanosatDB_munging/Countries-Continents.csv") %>%
  mutate(Country = case_when(Country == "CZ" ~ "Czech Republic",
                               Country == "Russian Federation" ~ "Russia",
                               Country == "US" ~ "United States",
                             TRUE ~ Country)) # all other values remain the same
```
# Add font
```{r}
font_add_google("Montserrat")
font_headlines <- "Montserrat"
font_add_google("Cousine")
font_text <- "Cousine"
# get the path of font awesome
fa_brands_path <- systemfonts::font_info(family = "Font Awesome 6 Brands")[["path"]]
# add the font under the name of "fa-brands"
font_add(family = "fa-brands", fa_brands_path)

showtext_auto()
```


# Data wrangling
```{r}
# Filter out all countries with less than 101 WWTP
Countries.morethan.100.wwtp <- WWTP.data %>%
  group_by(COUNTRY) %>%
  count() %>%
  filter(n > 100) %>%
  select(COUNTRY)

# Filter for countries with > 100 WWTPs
WWTP.data.filtered <- WWTP.data %>%
  filter(COUNTRY %in% Countries.morethan.100.wwtp$COUNTRY &
           STATUS != "Closed" &
           POP_SERVED != 0) %>%
# add continent column to the original dataset
  left_join(Continents.countries.list, by = c("COUNTRY" = "Country")) %>%
# calculate Discharge per person and the average for country and continent
  mutate(DischargePerPerson = WASTE_DIS/POP_SERVED) %>%
  group_by(COUNTRY) %>%
  mutate(DischargePerCountry = mean(DischargePerPerson)) %>%
  group_by(Continent) %>%
  mutate(DischargePerContinent = mean(DischargePerPerson)) %>%
  ungroup() %>%
  distinct(DischargePerCountry, .keep_all = T) %>%
  mutate(DischargePerPersonDiff = DischargePerContinent - DischargePerCountry) %>%
# sort by Discharge difference and
  arrange(DischargePerPersonDiff) %>%
# select the 5 highest positive and 5 highest negative differences
  .[c(1:5, (dim(.)[1]-4):(dim(.)[1])),] %>%
  select(c("COUNTRY", "Continent", "DischargePerCountry":"DischargePerContinent")) %>%
  pivot_longer(cols = c(DischargePerContinent, DischargePerCountry)) %>%
  rename("Scale" = "name",
         "DischargePerPerson" = "value") %>%
  mutate(Scale = case_when(Scale == "DischargePerCountry" ~ "Country",
                           Scale == "DischargePerContinent" ~ "Continent"))
  
WWTP.data.filtered$COUNTRY <- factor(WWTP.data.filtered$COUNTRY, 
                                     levels = c("South Africa",
                                                         "Canada",
                                                         "India",
                                                         "Ireland",
                                                         "Romania",
                                                         "Turkey",
                                                         "Iran",
                                                         "Mexico",
                                                         "Egypt",
                                                         "Algeria"
                                                         ))
# prepare data for the dumbbell plot
Continent <- WWTP.data.filtered %>%
  filter(Scale == "Continent")

Country <- WWTP.data.filtered %>%
  filter(Scale == "Country")
```

# Define strings to use in plot
```{r}
plottitle = "Average discharge per person per country worldwide compared to their respective continents average.<br>The Plot shows the top 5 countries discharging less (<span style='color:#7b9f66'>green</span>) and more (<span style='color: #d57e7e'>red</span>) than the average of the continent."

plotsubtitle = "Data based on countries with > 100 WWTPs."

plotcaption = str_wrap("Source: Macedo et al 2022 <span style='font-family:\"fa-brands\"'>&#xf09b;</span> DoZi93/TidyTuesday #TidyTuesday #rstats")
```

# Plot the dumbbell plot
```{r}
dumbbell.DischargeDiff.Country.Continent <- ggplot(data = WWTP.data.filtered) +
  geom_rect(xmin = min(WWTP.data.filtered$DischargePerPerson),
            xmax = 8,
            ymin = -Inf,
            ymax = 5.5,
            fill = "#D57E7E",
            alpha = 0.009) +
  geom_rect(xmin = min(WWTP.data.filtered$DischargePerPerson),
            xmax = 8,
            ymin = 5.5,
            ymax = Inf,
            fill = "#CEE5D0",
            alpha = 0.04) +
  geom_segment(aes(x = DischargePerPerson,
                   y = COUNTRY,
                   xend = Country$DischargePerPerson,
                   yend = Country$COUNTRY),
              alpha = .1,
              size = 2,
              data = Continent) +
  geom_point(aes(x = DischargePerPerson, y = COUNTRY, shape = Scale),
             size = 1.7,
             fill = "#a6c3f7",
             color = "black") +
  scale_shape_manual(values = c(22,21)) +
  theme_minimal() +
  ylab("") +
  xlab("\nDischarge per Person") +
  labs(title = plottitle,
       subtitle = plotsubtitle,
       caption = plotcaption) +
  xlim(values = c(0,8)) +
  theme(text = element_text(family = font_headlines,
                            color = "#000000"),
        legend.position = "top",
        legend.justification = "left",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        legend.text = element_text(size = 18),
        legend.key.size = unit(1.3, "line"),
        legend.margin = margin(t = -6),
        axis.text = element_text(size = 25),
        axis.title.x = element_text (size = 22,
                                     vjust = 6),
        plot.title = element_markdown(size = 19,
                                      lineheight = .5,
                                      family = font_text),
        plot.subtitle = element_markdown(size = 16,
                                         vjust = -1.3,
                                         family = font_text),
        plot.background = element_rect(fill = "#fafaf0",
                                       color = "#fafaf0"),
        plot.caption = element_markdown(size = 14),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_line(color = "grey70",
                                          size=0.1,
                                          linetype = "dashed")) +
  guides(shape = guide_legend(override.aes = list(size = 2.4)))

plot(dumbbell.DischargeDiff.Country.Continent)

ggsave("TidyTuesday_Week38.jpg")
```

